using System.Security.Cryptography;using System.Text;
namespace QuantForge.Core;
public sealed record NativeBuildEvidence(string EvidenceFingerprint,string Platform,string Commit,string Tree,string AppVersion,string BuildCode,string ArtifactName,string ArtifactSha256,long ArtifactBytes,int WarningCount,int ErrorCount,bool BuildPassed,bool ProductionSigned);
public static class NativeBuildEvidenceRules
{
 public static NativeBuildEvidence Create(string platform,string commit,string tree,string appVersion,string buildCode,string artifactName,string artifactSha256,long artifactBytes,int warningCount,int errorCount,bool buildPassed,bool productionSigned)
 {if(string.IsNullOrWhiteSpace(platform)||string.IsNullOrWhiteSpace(commit)||string.IsNullOrWhiteSpace(tree)||string.IsNullOrWhiteSpace(appVersion)||string.IsNullOrWhiteSpace(buildCode)||string.IsNullOrWhiteSpace(artifactName)||string.IsNullOrWhiteSpace(artifactSha256))throw new InvalidOperationException("Native build evidence identity is incomplete.");if(artifactBytes<0||warningCount<0||errorCount<0)throw new InvalidOperationException("Native build evidence counts are invalid.");if(buildPassed&&errorCount!=0)throw new InvalidOperationException("A passing native build cannot report compiler errors.");var text=string.Join("|",platform,commit,tree,appVersion,buildCode,artifactName,artifactSha256,artifactBytes,warningCount,errorCount,buildPassed,productionSigned);var fp=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(text)));return new(fp,platform,commit,tree,appVersion,buildCode,artifactName,artifactSha256,artifactBytes,warningCount,errorCount,buildPassed,productionSigned);}
 public static void Validate(NativeBuildEvidence value){var expected=Create(value.Platform,value.Commit,value.Tree,value.AppVersion,value.BuildCode,value.ArtifactName,value.ArtifactSha256,value.ArtifactBytes,value.WarningCount,value.ErrorCount,value.BuildPassed,value.ProductionSigned);if(expected!=value)throw new InvalidOperationException("Native build evidence fingerprint is invalid.");}
}
